Vagrant.configure("2") do |config|

  config.vm.define "redis" do |machine|
    machine.vm.provision :shell, :inline => "chmod +x /vagrant/setup-ubuntu.sh"
    machine.vm.provision :shell, :inline => "/vagrant/setup-ubuntu.sh"
    machine.vm.provision :shell, :inline => "chmod +x /vagrant/build-redis.sh"
    machine.vm.provision :shell, :inline => "/vagrant/build-redis.sh"
    machine.vm.box = "precise64"
    machine.vm.box_url = "http://files.vagrantup.com/precise64.box"
    machine.vm.provider "virtualbox" do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

end